web:
 restart: always
 image: tutum/apache-php
 ports:
  - "80:80"
 volumes:
  - /var/www:/var/www
  - /var/www/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
  - /var/www/docker/sites:/etc/apache2/sites-enabled
 environment:
  - ALLOW_OVERRIDE=true
 links:
  - db:db
  - gogs:gogs

db:
 image: mysql
 restart: always
 volumes:
  - /var/lib/boot2docker/mysql:/var/lib/mysql
 environment:
  - MYSQL_ROOT_PASSWORD=root

gogs:
 restart: always
 image: gogs/gogs
 ports: 
  - "10022:22"
  - "10080:3000"
 volumes:
  - /var/gogs:/data gogs/gogs